"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { CheckCircle2, Copy, Loader2 } from "lucide-react";

import {
  StopEditor,
  createInitialStops,
  type EditableStop,
} from "@/components/admin/stop-editor";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/toast";
import { createDeliveryAction } from "@/lib/admin/actions";
import { isValidLatitude, isValidLongitude } from "@/lib/format";

type CustomerOption = {
  id: string;
  full_name: string;
  email: string;
};

export function DeliveryForm({ customers }: { customers: CustomerOption[] }) {
  const router = useRouter();
  const { success, error: toastError } = useToast();
  const [pending, startTransition] = useTransition();
  const [customerId, setCustomerId] = useState("");
  const [referenceNumber, setReferenceNumber] = useState("");
  const [description, setDescription] = useState("");
  const [weight, setWeight] = useState("");
  const [stops, setStops] = useState<EditableStop[]>(createInitialStops());
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<{
    id: string;
    tracking_number: string;
  } | null>(null);
  const [copied, setCopied] = useState(false);

  function validate(): string | null {
    if (!customerId) return "Please select a customer.";
    if (stops.length < 2) return "Origin and destination are required.";
    for (const [index, stop] of stops.entries()) {
      if (!stop.name.trim()) return `Enter a name for stop ${index + 1}.`;
      if (!isValidLatitude(stop.latitude)) {
        return `Latitude for stop ${index + 1} must be between -90 and 90.`;
      }
      if (!isValidLongitude(stop.longitude)) {
        return `Longitude for stop ${index + 1} must be between -180 and 180.`;
      }
    }
    return null;
  }

  function onSubmit(event: React.FormEvent) {
    event.preventDefault();
    const validationError = validate();
    if (validationError) {
      setError(validationError);
      return;
    }

    setError(null);
    startTransition(async () => {
      const result = await createDeliveryAction({
        customerId,
        referenceNumber,
        description,
        weight,
        stops: stops.map(({ name, latitude, longitude }) => ({
          name,
          latitude,
          longitude,
        })),
      });

      if (!result.ok) {
        setError(result.error);
        toastError("Unable to create delivery.");
        return;
      }

      setCreated({
        id: result.data.id,
        tracking_number: result.data.tracking_number,
      });
      success("Delivery created successfully.");
      router.refresh();
    });
  }

  if (created) {
    return (
      <Card className="max-w-xl">
        <CardHeader>
          <div className="mb-2 inline-flex size-10 items-center justify-center rounded-full bg-success/15 text-success">
            <CheckCircle2 className="size-5" aria-hidden />
          </div>
          <CardTitle>Delivery Created</CardTitle>
          <CardDescription>
            Tracking number generated by the backend. Share it with the customer
            for public tracking.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="rounded-lg border border-border bg-muted/40 p-4">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">
              Tracking Number
            </p>
            <p className="mt-1 font-mono text-xl font-semibold">
              {created.tracking_number}
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button asChild>
              <Link href={`/admin/deliveries/${created.id}`}>View Delivery</Link>
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={async () => {
                await navigator.clipboard.writeText(created.tracking_number);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
            >
              <Copy className="size-4" aria-hidden />
              {copied ? "Copied" : "Copy Tracking Number"}
            </Button>
            <Button asChild variant="ghost">
              <Link href="/admin/deliveries">Back to list</Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (customers.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>No customers available</CardTitle>
          <CardDescription>
            Create a customer before assigning a delivery.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Button asChild>
            <Link href="/admin/customers/new">Create Customer</Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <form onSubmit={onSubmit} className="space-y-6" noValidate>
      <Card>
        <CardHeader>
          <CardTitle>Customer & parcel</CardTitle>
          <CardDescription>
            Assign this shipment to an existing customer in your company.
          </CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-2">
          <div className="space-y-2 md:col-span-2">
            <Label htmlFor="customer">Customer</Label>
            <select
              id="customer"
              value={customerId}
              onChange={(event) => setCustomerId(event.target.value)}
              className="flex h-10 w-full rounded-md border border-input bg-card px-3 text-sm"
              required
            >
              <option value="">Select customer</option>
              {customers.map((customer) => (
                <option key={customer.id} value={customer.id}>
                  {customer.full_name} ({customer.email})
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="reference">Reference number</Label>
            <Input
              id="reference"
              value={referenceNumber}
              onChange={(event) => setReferenceNumber(event.target.value)}
              placeholder="Optional internal reference"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="weight">Weight (kg)</Label>
            <Input
              id="weight"
              type="number"
              min="0"
              step="any"
              value={weight}
              onChange={(event) => setWeight(event.target.value)}
              placeholder="Optional"
            />
          </div>
          <div className="space-y-2 md:col-span-2">
            <Label htmlFor="description">Description</Label>
            <textarea
              id="description"
              value={description}
              onChange={(event) => setDescription(event.target.value)}
              placeholder="Optional parcel notes"
              rows={3}
              className="flex w-full rounded-md border border-input bg-card px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            />
          </div>
        </CardContent>
      </Card>

      <StopEditor stops={stops} onChange={setStops} />

      {error ? (
        <p
          className="rounded-md border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive"
          role="alert"
        >
          {error}
        </p>
      ) : null}

      <div className="flex flex-wrap gap-2">
        <Button type="submit" disabled={pending}>
          {pending ? (
            <>
              <Loader2 className="size-4 animate-spin" aria-hidden />
              Creating delivery…
            </>
          ) : (
            "Create Delivery"
          )}
        </Button>
        <Button asChild type="button" variant="outline">
          <Link href="/admin/deliveries">Cancel</Link>
        </Button>
      </div>
    </form>
  );
}
